k2-fsa/snowfall

- egs/librispeech/asr/simple_v1/train_fast.py
This makes cycles of testing faster.
Note: you have to use the latest k2 because I just added as_dict() and from_dict().
> Add shortcut for loading LG

- egs/librispeech/asr/simple_v1/prepare.py
I think this might've been an omission rather than an intention to leave out the non-augmented data in the training. This augmentation setup might still not be perfect, but it's a step closer to what we would have typically done.
> Add non-augmented data in training

- egs/librispeech/asr/simple_v1/prepare.py
for #13 and https://github.com/lhotse-speech/lhotse/issues/126
> Fix the issue #13 by wrapping the codes with a main()

- egs/librispeech/asr/simple_v1/prepare.py
For issue https://github.com/k2-fsa/snowfall/issues/18
> fix prepare.py slow speed

- egs/librispeech/asr/simple_v1/train.py
Now creation of the decoding graphs is the slowest part.
> Changing dense pruned intersection to un-pruned (faster).

- egs/librispeech/asr/simple_v1/decode.py
- snowfall/decoding/graph.py
> [WIP] some changes about decoding

- .gitignore
- egs/aishell/asr/simple_v1/aishell.py
- egs/aishell/asr/simple_v1/decode.py
- egs/aishell/asr/simple_v1/local
- egs/aishell/asr/simple_v1/local2/aishell_data_prep.sh
- egs/aishell/asr/simple_v1/local2/aishell_prepare_dict.sh
- egs/aishell/asr/simple_v1/local2/aishell_train_lms.sh
- egs/aishell/asr/simple_v1/local2/download_and_untar.sh
- egs/aishell/asr/simple_v1/path.sh
- egs/aishell/asr/simple_v1/prepare.py
- egs/aishell/asr/simple_v1/run.sh
- egs/aishell/asr/simple_v1/train.py
- tools/install_kaldi_lm.sh
take example by #57 and other previous pr, make a recipe with aishell mandarin dataset
result is
```
2020-12-28 10:18:09,533 INFO [decode.py:222] %WER 23.62% [15221 / 64428, 1372 ins, 1847 del, 12002 sub ]
2020-12-28 10:18:09,533 INFO [decode.py:226] %CER 14.49% [15180 / 104765, 415 ins, 418 del, 14347 sub ]
```
@danpovey @csukuangfj please have a review
> add aishell recipe

- egs/aishell/asr/simple_v1/decode.py
- egs/librispeech/asr/simple_v1/decode.py
Increase max_frames from 30000 to 100000. 
The detailed comparison is in https://github.com/k2-fsa/k2/pull/559#issuecomment-752017215
> Increase max_frames to speed up decoding

- egs/aishell/asr/simple_v1/prepare.py
- egs/librispeech/asr/simple_v1/local/filter_scp.pl
fix aishell recipe run error : missing filter_scp.pl and 'import sys'
> fix aishell recipe : missing filter_scp.pl and 'import sys'

- egs/librispeech/asr/simple_v1/asg_train.py
`model.P_scores` is initialized to zeros, you can see that arc scores of phone `AE` are all ones (i.e., log(1) == 0).
```
+--------+------------+----------+----------+----------+----------+----------+----------+----------+----------+-----------+----------+----------+-----------+-----------+----------+----------+----------+----------+----------+----------+----------+----------+----------+----------+----------+----------+----------+----------+----------+-----------+-----------+----------+----------+-----------+----------+----------+-----------+----------+----------+----------+----------+----------+----------+----------+----------+----------+----------+-----------+-----------+----------+----------+-----------+-----------+----------+----------+-----------+-----------+-----------+-----------+-- …
```
> initialize model.P_scores with all zeros.

- egs/librispeech/asr/simple_v1/mmi_bigram_train.py
- egs/librispeech/asr/simple_v1/train.py
This PR should be merged when https://github.com/k2-fsa/k2/pull/587 get merged as there's some API changes in k2 (actually only `get_tot_scores`)
Wondering what python formatter you guys use, seems there's a lot of automatic style changes at my side...
> sync snowfall with k2 change

- egs/librispeech/asr/simple_v1/RESULTS.md
- egs/librispeech/asr/simple_v1/ctc_decode.py
- egs/librispeech/asr/simple_v1/mmi_bigram_decode.py
- egs/librispeech/asr/simple_v1/mmi_mbr_decode.py
- egs/librispeech/asr/simple_v1/mmi_mbr_train.py
- egs/librispeech/asr/simple_v1/prepare.py
- egs/librispeech/asr/simple_v1/run.sh
- snowfall/decoding/graph.py
- snowfall/training/mmi_mbr_graph.py
~working in progress.~
---
Ready for review.
> MMI + MBR training

- egs/aishell/asr/simple_v1/RESULTS
- egs/aishell/asr/simple_v1/RESULTS.md
- egs/aishell/asr/simple_v1/ctc_decode.py
- egs/aishell/asr/simple_v1/ctc_train.py
- egs/aishell/asr/simple_v1/local2/aishell_train_lms.sh
- egs/aishell/asr/simple_v1/mmi_bigram_decode.py
- egs/aishell/asr/simple_v1/mmi_bigram_train.py
- egs/aishell/asr/simple_v1/run.sh
aishell recipe : 
1)  fix typo 
2)  sync with latest K2
3) add mmi_bigram RESULT
> aishell recipe : fix typo && sync with latest K2

- egs/aishell/asr/simple_v1/RESULTS.md
- egs/aishell/asr/simple_v1/ctc_train.py
- egs/aishell/asr/simple_v1/local2/aishell_train_lms.sh
- egs/aishell/asr/simple_v1/prepare.py
- egs/aishell/asr/simple_v1/run.sh
[log-train-2021-02-12-14-19-11.txt](https://github.com/k2-fsa/snowfall/files/5971503/log-train-2021-02-12-14-19-11.txt)
https://tensorboard.dev/experiment/5bMFoRjVT7OMRWVFd3qVAA/#scalars
Decoding results of each epoch (the first line is WER and the second CER) are listed below. They are obtained using the latest k2 and lhotse as of today (2021-02-12).
```
2021-02-12 17:15:21,695 INFO [ctc_decode.py:182] %WER 28.79% [18552 / 64428, 1612 ins, 2177 del, 14763 sub ]
2021-02-12 17:15:21,696 INFO [ctc_decode.py:186] %WER 19.35% [20274 / 104767, 591 ins, 599 del, 19084 sub ]
2021-02-12 17:18:12,417 INFO [ctc_decode.py:182] %WER 26.12% [16829 / 64428, 1454 ins, 2083 del, 13292 sub ]
2021-02-12 17:18:12,417 INFO [ctc_decode.py:186] %WER 16.75% [17548 / 104767, 385 ins, 598 del, 16565 sub ] …
```
> Add CTC training results for the AIShell recipe.

- egs/aishell/asr/simple_v1/RESULTS.md
add RESULT detail for MMI training
> AIShell : add RESULT detail for MMI training

- egs/librispeech/asr/simple_v1/RESULTS.md
- egs/librispeech/asr/simple_v1/mmi_att_transformer_decode.py
- egs/librispeech/asr/simple_v1/mmi_att_transformer_train.py
- snowfall/models/conformer.py
- snowfall/models/transformer.py
For librispeech, conformer achives 6.84% WER, while transformer is 7.72%.
This PR also reduce warmup steps from 25k to 5k. After this modification, we could get comparable results in 10 epochs.
> Support Conformer

- egs/aishell/asr/simple_v1/ctc_decode.py
- egs/aishell/asr/simple_v1/mmi_bigram_decode.py
- egs/librispeech/asr/simple_v1/ctc_att_transformer_decode.py
- egs/librispeech/asr/simple_v1/ctc_decode.py
- egs/librispeech/asr/simple_v1/mmi_att_transformer_decode.py
- egs/librispeech/asr/simple_v1/mmi_bigram_decode.py
- egs/librispeech/asr/simple_v1/mmi_mbr_decode.py
- snowfall/decoding/graph.py
- snowfall/training/mmi_mbr_graph.py
> Renaming LG -> HLG

- egs/aishell/asr/simple_v1/RESULTS.md
- egs/aishell/asr/simple_v1/mmi_att_transformer_decode.py
- egs/aishell/asr/simple_v1/mmi_att_transformer_train.py
1. add conformer to AISHELL recipe 
2. report experiment result (conformer model)
> add conformer to AISHELL recipe and report result

- egs/librispeech/asr/simple_v1/mmi_att_transformer_decode.py
- egs/librispeech/asr/simple_v1/mmi_att_transformer_train.py
- egs/librispeech/asr/simple_v1/prepare.py
- snowfall/common.py
Note: this is un-tested yet, I'll run it once I'm able to...
> Add dev-other and test-other to librispeech recipe

- egs/librispeech/asr/simple_v1/RESULTS.md
- egs/librispeech/asr/simple_v1/mmi_att_transformer_decode.py
- egs/librispeech/asr/simple_v1/mmi_att_transformer_train.py
- egs/librispeech/asr/simple_v1/prepare.py
The best result I got is:
```
2021-03-26 19:23:07,097 INFO [mmi_att_transformer_decode.py:331] [test-clean] %WER 6.90% [3627 / 52576, 502 ins, 310 del, 2815 sub ]
2021-03-26 19:24:50,661 INFO [mmi_att_transformer_decode.py:331] [test-other] %WER 17.89% [9363 / 52343, 1141 ins, 908 del, 7314 sub ]
```
It requires going from 40 to 80 filter banks (it reduces the WER by ~0.5% on test-other). The result for 40 is in RESULTS.md.
Also I made tensorboard optional (I was opening too many files for some reason and hit the OS limit several times).
> Add specaugment

- egs/librispeech/asr/simple_v1/RESULTS.md
> Add missing results for ctc conformer training with SpecAug

- egs/librispeech/asr/simple_v1/mmi_att_transformer_train.py
The training time is approximately halved using two GPUs.
But it got stuck at the line
```python
cleanup_dist()
```
when the training was about to finish. So only checkpoints up to `epoch-8.pt` are available.
The decoding results with model averaging using the last 5 checkpoints are
```
2021-04-02 09:31:15,951 INFO [common.py:356] [test-clean] %WER 7.11% [3736 / 52576, 487 ins, 314 del, 2935 sub ]
2021-04-02 09:33:42,194 INFO [common.py:356] [test-other] %WER 18.50% [9686 / 52343, 1080 ins, 889 del, 7717 sub ]
```
The DDP training seems working.
---
After removing `cleanup_dist()` and testing it with a small amount of data, the training process is able to finish in a correct way.
The training process is started again and will run for 10 epochs. I will report the result here after it …
> Support multi-GPU training with DDP from PyTorch.

- egs/librispeech/asr/simple_v1/mmi_att_transformer_train.py
- snowfall/dist.py
> Revert "Make master port configurable"

- egs/librispeech/asr/simple_v1/ctc_att_transformer_decode.py
- egs/librispeech/asr/simple_v1/mmi_att_transformer_decode.py
- egs/librispeech/asr/simple_v1/mmi_att_transformer_train.py
- egs/librispeech/asr/simple_v1/mmi_bigram_decode.py
- egs/librispeech/asr/simple_v1/mmi_bigram_train.py
- egs/librispeech/asr/simple_v1/prepare.py
> Print default values in the help message.

- snowfall/common.py
After the recent changes, the script crashed when trying to resume training.
> Fix loading checkpoints with DDP

- snowfall/decoding/lm_rescore.py
- snowfall/objectives/mmi.py
- snowfall/training/mmi_graph.py
Related to #165 
Need to verify that it improves training speed.
> Invoke k2.intersect_dense and get_tot_scores only once in LFMMILoss

- egs/librispeech/asr/simple_v1/mmi_att_transformer_train.py
- snowfall/common.py
- snowfall/data/asr_datamodule.py
- snowfall/training/diagnostics.py
My initial estimate is that we can use about 1.5x larger batches per GPU with these changes. I was using `max_duration=450`, and so far 200 batches into training with `max_duration=700` it seems to be working. 
I'll train a full model and report the results. They shouldn't be affected.
> Mixed precision training

- egs/librispeech/asr/simple_v1/local/prepare_lang.sh
easy to miss when playing with multiple lexicons..
> Fix hardcoded librispeech lang dir in local/prepare_lang.sh

- snowfall/common.py
this small change makes is so that get_texts() works with https://github.com/k2-fsa/k2/pull/749, which makes a certain property not ragged that was formerly ragged.  (I don't have time to work out precisely why).
The code is back compatible.
> fix get_texts() to work with recent changes in k2.

- egs/librispeech/asr/simple_v1/mmi_att_transformer_decode.py
- snowfall/common.py
- snowfall/decoding/graph.py
- snowfall/decoding/lm_rescore.py
Closes #211 
@danpovey Please try this pull-request.
It requires a pull request I just created in k2 to clear the cache of an FAS if its scores are reassigned.
> Add lm_scale to LM rescoring.

- snowfall/models/transformer.py
Reference: 
https://github.com/pytorch/pytorch/pull/60631
> faster generate_square_subsequent_mask
