- egs/librispeech/asr/simple_v1/decode.py
- egs/librispeech/asr/simple_v1/train.py
It seems there is a small bug in train.py and decode.py. In train.py：
supervision_segments = supervision_segments[indices]
texts = supervisions['text']
assert feature.ndim == 3
The "texts" is not reorder by indices, while supervision_segments have been reorder. And in decode.py there is same bug.
I reorder "texts" by indices and retrain the model, the WER reduce to 87.01% after 5 epoches.
> reorder texts by indices

- egs/aishell/asr/simple_v1/ctc_decode.py
- egs/aishell/asr/simple_v1/ctc_train.py
- egs/aishell/asr/simple_v1/mmi_bigram_decode.py
- egs/aishell/asr/simple_v1/mmi_bigram_train.py
- egs/librispeech/asr/simple_v1/ctc_decode.py
- egs/librispeech/asr/simple_v1/ctc_train.py
- egs/librispeech/asr/simple_v1/mmi_bigram_decode.py
- egs/librispeech/asr/simple_v1/mmi_bigram_train.py
- egs/librispeech/asr/simple_v1/mmi_mbr_decode.py
- egs/librispeech/asr/simple_v1/mmi_mbr_train.py
Reflects the changes from https://github.com/lhotse-speech/lhotse/pull/194
This new version allows working with distributed training out-of-the-box. Once it is merged, I will rebase #71 on that and finish multi-GPU training support.
One thing I am concerned about is the number of files with duplicate code. It becomes quite labor-intensive to propagate these kinds of changes, and I am not sure if I'm doing everything OK as I can't run all of these (🙏🏻 static checker tool helps 🙏🏻). It could be good to slowly converge to some common code structure that can be shared and imported (e.g. a `Trainer` class or something like that)?
> Sync snowfall with Lhotse's dataset/sampler refactoring PR

- egs/librispeech/asr/simple_v1/RESULTS.md
Add training results for the LibriSpeech recipe, like https://github.com/k2-fsa/snowfall/pull/99, 
- LibriSpeech CTC training  (TDNN-LSTM): [log-train-2021-02-16-12-36-09.txt](https://github.com/k2-fsa/snowfall/files/5995756/log-train-2021-02-16-12-36-09.txt)
- LibriSpeech MMI training  (TDNN-LSTM): [log-train-2021-02-16-12-36-23.txt](https://github.com/k2-fsa/snowfall/files/5995759/log-train-2021-02-16-12-36-23.txt)
- LibriSpeech MMI+MBR training  (TDNN-LSTM): [log-train-2021-02-17-01-10-23.txt](https://github.com/k2-fsa/snowfall/files/5995761/log-train-2021-02-17-01-10-23.txt)
- LibriSpeech CTC training  (Transformer): [log-train-2021-02-16-02-27-50.txt](https://github.com/k2-fsa/snowfall/files/5995766/log-train-2021-02-16-02-27-50.txt)
- LibriSpeech MMI training  (Transformer): …
>  Add training results for the LibriSpeech recipe.

- egs/librispeech/asr/simple_v1/mmi_att_transformer_decode.py
- egs/librispeech/asr/simple_v1/mmi_att_transformer_train.py
- egs/librispeech/asr/simple_v1/mmi_bigram_train.py
- egs/librispeech/asr/simple_v1/prepare.py
In addition to the changes mentioned in #108, I am running the training on full libri to see what's the gap between our recipe and SOTA. I increased the model size (attention dim 256 -> 512 and nheads 4 -> 8) to resemble the ESPnet setup more closely. So far I've trained up until 6th epoch and the WER for averaged model on the 3 last epochs is 6.03%. It is improving each epoch so I will keep training and we'll see where we get.
> Args for bucketing and concatenation, option to train on full librispeech

- egs/aishell/asr/simple_v1/ctc_decode.py
- egs/aishell/asr/simple_v1/ctc_train.py
- egs/aishell/asr/simple_v1/mmi_att_transformer_decode.py
- egs/aishell/asr/simple_v1/mmi_att_transformer_train.py
- egs/aishell/asr/simple_v1/mmi_bigram_decode.py
- egs/aishell/asr/simple_v1/mmi_bigram_train.py
- egs/librispeech/asr/simple_v1/ctc_att_transformer_decode.py
- egs/librispeech/asr/simple_v1/ctc_att_transformer_train.py
- egs/librispeech/asr/simple_v1/ctc_decode.py
- egs/librispeech/asr/simple_v1/ctc_train.py
- egs/librispeech/asr/simple_v1/mmi_att_transformer_decode.py
- egs/librispeech/asr/simple_v1/mmi_att_transformer_train.py
- egs/librispeech/asr/simple_v1/mmi_bigram_decode.py
- egs/librispeech/asr/simple_v1/mmi_bigram_train.py
- egs/librispeech/asr/simple_v1/mmi_mbr_decode.py
- egs/librispeech/asr/simple_v1/mmi_mbr_train.py
This is how on-the-fly feature extraction would look like. The main differences are that:
- the cuts (speech and noise) are mixed and padded in the time domain, not fbank domain
- there is no lilcom compression
- [not in this PR yet] speed perturbation could be applied stochastically; instead of creating 3x larger epochs, we can have 3x more epochs and apply perturbation with a given probability
I think I will revert `'inputs'` key back to `'features'` in batches, and replace `max_frames` everywhere with `max_duration` (the relationship is simple - multiply duration by 100 and you have the num_frames). I'll also add option to `prepare.py` not to extract features.
Preliminary results are actually worse for on-the-fly variant, but I haven't figured out why yet. I'll have to inspect the …
> [WIP] Training with on-the-fly feature extraction

- egs/librispeech/asr/simple_v1/ctc_att_transformer_decode.py
- egs/librispeech/asr/simple_v1/ctc_att_transformer_train.py
- egs/librispeech/asr/simple_v1/prepare.py
Closes #142 
---
- Tensorboard log <https://tensorboard.dev/experiment/s5iepd7PQBmzKOodcMH6Wg/>
- Training log [log-train-2021-03-29-18-17-44.txt](https://github.com/k2-fsa/snowfall/files/6225743/log-train-2021-03-29-18-17-44.txt)
> Add results for CTC conformer training with SpecAug

- .gitignore
- egs/aishell/asr/simple_v1/mmi_att_transformer_decode.py
- egs/aishell/asr/simple_v1/mmi_att_transformer_train.py
- egs/librispeech/asr/simple_v1/mmi_att_transformer_decode.py
- egs/librispeech/asr/simple_v1/mmi_att_transformer_train.py
- snowfall/data/__init__.py
- snowfall/data/aishell.py
- snowfall/data/asr_datamodule.py
- snowfall/data/datamodule.py
- snowfall/data/librispeech.py
Guys, take a look and let me know if you think this makes sense. I thought about this a bit and I think there are four main "modules" in snowfall:
- data pipeline (cuts/augmentation/dataloaders)
- models (e.g. conformer and its settings)
- training/testing loop structure
- loss functions (e.g. CTC, MMI, others and how they interact with lexicon/LM graphs)
I think they are 80% orthogonal and the 20% that interleaves is probably the tricky part to structure this in the right way. I think each of them should be structured into some sort of module that registers arguments in an `argparse.ArgumentParser`, and we can use `jsonargparse` later to keep the configuration in YAML files (this seems to work fine in ESPnet, it's also a bit similar to how Kaldi did it).
This PR is dealing with the data …
> Refactoring: data pipeline

- egs/librispeech/asr/simple_v1/RESULTS.md
- egs/librispeech/asr/simple_v1/local/download_lm.sh
- egs/librispeech/asr/simple_v1/mmi_att_transformer_decode.py
- egs/librispeech/asr/simple_v1/run.sh
- snowfall/decoding/graph.py
- snowfall/decoding/lm_rescore.py
~Support for rescoring with the whole lattice is not added yet, as k2 does not support removing epsilon self-loops at present.~
Here are the WERs (%) using LM rescoring. You can see that rescoring with LM reduces WER.
It uses `k2.shortest_path` for decoding
- test_clean: 6.80
- test_other: 18.03
It uses `k2.random_paths` with various `num_paths`
> Rescoring with 4-gram LM

- egs/librispeech/asr/simple_v1/ctc_decode.py
- egs/librispeech/asr/simple_v1/ctc_train.py
- egs/librispeech/asr/simple_v1/mmi_att_transformer_train.py
It improves converging speed.
This pull-request is just a refactoring of danpovey's work.
The following is a screenshot comparing the obj with and without ali_model.
You can see that the objf with ali_model (using this pull-request) is lower.
> Use pre-trained CTC model for conformer training.

- egs/librispeech/asr/simple_v1/RESULTS.md
- egs/librispeech/asr/simple_v1/mmi_att_transformer_decode.py
- egs/librispeech/asr/simple_v1/mmi_att_transformer_train.py
- snowfall/models/conformer.py
- snowfall/models/transformer.py
This PR is from https://github.com/k2-fsa/snowfall/pull/181. 
There are results before and after adding VGG frontend:
- Without LM rescoring:
model | test-clean | test-other
-- | -- | --
Conformer | 6.79 | 17.8
Conformer + VGG | 6.65 | 17.68
- With LM rescoring:
model | test-clean | test-other
-- | -- | --
Conformer | 5.77 | 15.47
Conformer + VGG | 5.55 | 15.32
We can see the VGG frontend could slightly improve the results.
- Tensorboard log: https://tensorboard.dev/experiment/qBApmvzqQ7SgFjatzMFPmw/
- Training log:  [log-train-0-2021-05-01-14-41-08.txt](https://github.com/k2-fsa/snowfall/files/6410691/log-train-0-2021-05-01-14-41-08.txt)
> Add VGG frontend

- snowfall/models/conformer.py
- snowfall/models/transformer.py
Fix two transformer/conformer bugs when normalize_before is false. 
- In transformer, argument `normalize_before` is not passed to encoder/decoder layers
- In conformer, when set `normalize_before = False`, there is a repeated LayerNorm.
Thanks to review from @csukuangfj !
> Fix transformer/conformer bugs when normalize_before is false

- egs/librispeech/asr/simple_v1/mmi_att_transformer_train.py
- egs/librispeech/asr/simple_v1/run.sh
- snowfall/objectives/mmi.py
Relates https://github.com/k2-fsa/k2/issues/739
@jarvan-Wang
Could you try this pull request?
Please add the following command-line option while running the script:
```
--use-pruned-intersect=1
```
---
From https://github.com/k2-fsa/k2/issues/739#issuecomment-843077996
> or to do the den decoding separately from the num
forward-backward with intersect_dense_pruned() which allows you to use a
single FSA instead of
multiple FSAs.  That would also be more suitable since the den graph is too
large.
Fangjun, at some point we should probably create an option in the training
code (or simply an alternative code path) which is efficient
when the den graph is inconveniently large.
An option is added to let the user make the decision whether the graph is large or not.
---
I only run the script for …
> Support using k2.intersect_dense_pruned in computing LF-MMI loss.

- egs/librispeech/asr/simple_v1/mmi_att_transformer_decode.py
- egs/librispeech/asr/simple_v1/mmi_att_transformer_train.py
- snowfall/models/conformer.py
Conformer structure differences are identified by loading espnet trained model into snowfall. https://github.com/k2-fsa/snowfall/pull/201
1. snowfall only scaling q; while espnet scale attn_output_weights.
2. espnet conformer has an extra layer_norm after encoder
With these two modifications and 30 epoch training, final result is a bit better(3.69 < 3.86 as reported in https://github.com/k2-fsa/snowfall/issues/154) than otherwise. 
Could you help verify their effectiveness (maybe they are just training variance)? @zhu-han @pzelasko 
BTW,  is there any mathmatics background which explains when to scaling during attn_output_weights computation? I read several papers, but failed to find a clue about this.
Rescoring WITH 4-gram lm lattice rescore
with modifications of this pr
```
avg epoch …
```
> espnet-style attn_output_weight scaling and extra after-norm layer

- egs/librispeech/asr/simple_v1/run.sh
- snowfall/training/ctc_graph.py
This implements the topo mentioned in
https://github.com/k2-fsa/k2/issues/746#issuecomment-856421616
Some examples (assuming there are three phones: a, b, c)
CAUTION: There are no mandatory blanks between the two consecutive symbols `aa` in `aabc`.
> Use a modified ctc_topo.

- egs/librispeech/asr/simple_v1/mmi_att_transformer_decode.py
The results of using 1-best and n-best decoding are given below:
The column in `nbest` indicates the size of `n` in `n-best`.
----
Detailed WERs are shown below:
```
#
```
`n-best` decoding without an LM does not seem to outperform 1-best decoding when no LM is used.
Anyway, it shows how we can use k2 for n-best decoding.
> Implement n-best decoding without an LM.

- snowfall/decoding/lm_rescore.py
See https://github.com/k2-fsa/snowfall/pull/201#discussion_r647975506
> The 2nd arg to get_tot_scores() here, representing log_semiring, should be false, because ARPA-type language models are constructed in such a way that the backoff prob is included in the direct arc. I.e. we would be double-counting if we were to sum the probabilities of the non-backoff and backoff arcs.
Change log_semiring to tropical_semiring indeed improves the WER. For the test-clean dataset, when num_paths is 100
and lm_scale=1.2, the WER decreases from 6.06 to 5.98.
> Use tropical semiring for lm_paths.get_tot_scores

- egs/librispeech/asr/simple_v1/bpe_ctc_att_conformer_decode.py
- egs/librispeech/asr/simple_v1/bpe_run.sh
- snowfall/models/conformer.py
- snowfall/models/transformer.py
- snowfall/text/numericalizer.py
This pr release a snowfall trained model together with related decode code. 
Wer on test-clean is lower than [previously trained model](https://github.com/k2-fsa/snowfall/pull/204) with snowfall, detailed comparison as following:
avg epoch 26-30 | no rescore | no rescore | 4-gram lattice rescore | 4-gram lattice rescore
-- | -- | -- | -- | --
&nbsp; | test-clean | test-other | test-clean | test-other
[before with LF-MMI loss](https://github.com/k2-fsa/snowfall/pull/204)| 4.14 | 8.41 | 3.69 | 7.68
current | 3.97 | 9.78 | * | *
```
INFO:root:[test-clean] %WER 3.97% [2087 / 52576, 220 ins, 166 del, 1701 sub ]
INFO:root:[test-other] %WER 9.78% [5121 / 52343, 535 ins, 439 del, 4147 sub ]
```
A thing worth to mention is that： current no-rescore result(3.97 on test-clean) is got WITHOUT a …
> bpe ctc decoder with a released model

- egs/librispeech/asr/simple_v1/.gitignore
- egs/librispeech/asr/simple_v1/local/add_silence_to_transcript.py
- egs/librispeech/asr/simple_v1/local/convert_transcript_to_corpus.py
- egs/librispeech/asr/simple_v1/local/make_kn_lm.py
- egs/librispeech/asr/simple_v1/mmi_att_transformer_decode.py
- egs/librispeech/asr/simple_v1/mmi_att_transformer_train.py
- egs/librispeech/asr/simple_v1/run.sh
- snowfall/common.py
- snowfall/decoding/lm_rescore.py
- snowfall/objectives/mmi.py
- snowfall/training/mmi_graph.py
Will post the result (the WER, probably tomorrow) when it is available.
---
Here is the information about the size of P when the number of phones is 86.
|            | current P | pre-trained P | pre-trained P after epsilon removal |
|------------|-----------|---------------|-------------------------------------|
| num_states | 88        | 74            | 74                                  |
| num_arcs   | 7568      | 3634          | 7209                                |
If we are going to use word pieces with vocab_size 5000, hope that P is not going to increase its size quadratically.
Will show the size of P for word pieces soon.
> Use a pre-trained bigram P for LF-MMI training

- snowfall/decoding/lm_rescore.py
https://github.com/k2-fsa/k2/pull/771 added support for CUDA to k2.connect.
This pull-request updates the code in snowfall to use that feature, which makes the rescoring process much faster.
The following are some decoding logs from one of my models for test-other. You can see that when `k2.connect` runs on CUDA, the decoding time is reduced from 27 minutes to 1.5 minutes.  (n-best list rescoring with max_duration=200)
```
2021-07-10 20:06:38,929 INFO [mmi_att_transformer_decode_2nd.py:540] * DECODING: test-other
2021-07-10 20:06:59,215 INFO [mmi_att_transformer_decode_2nd.py:229] batch 0, cuts processed until now is 0/2939 (0.000000%)
2021-07-10 20:08:36,257 INFO [mmi_att_transformer_decode_2nd.py:229] batch 10, cuts processed until now is 299/2939 (10.173528%)
2021-07-10 20:12:01,184 …
```
> Run k2.connect on CUDA.

- egs/aishell/asr/simple_v1/mmi_att_transformer_decode.py
- egs/gigaspeech/asr/simple_v1/asr_datamodule.py
- egs/gigaspeech/asr/simple_v1/ctc_decode.py
- egs/gigaspeech/asr/simple_v1/mmi_att_transformer_decode.py
- egs/gigaspeech/asr/simple_v1/prepare.py
- egs/librispeech/asr/simple_v1/bpe_ctc_att_conformer_decode.py
- egs/librispeech/asr/simple_v1/ctc_att_transformer_decode.py
- egs/librispeech/asr/simple_v1/ctc_decode.py
- egs/librispeech/asr/simple_v1/mmi_att_transformer_decode.py
- snowfall/data/asr_datamodule.py
This PR removes any mentions of arrow/pyarrow and uses lazy JSONL loading for the manifests. It also adjusts the arguments to K2SpeechRecognitionDataset. As a bonus, there's a torchscript conversion in GigaSpeech decoding which I find handy. I verified that I'm able to start and run the GigaSpeech L training with both Lhotse and Snowfall PRs. I also adjusted the dataloading stuff for LibriSpeech/Aishell in the same way, but haven't run them.
Sorry for the reformatting of asr_datamodule.py, hopefully the diff is not too messed up.
The corresponding Lhotse PR is https://github.com/lhotse-speech/lhotse/pull/345. These two PRs should be merged together; I'll wait for either @danpovey or @csukuangfj to ack before merging both.
> Complimentary sampler update following Lhotse's changes
